Repository KendallDoesCoding/mogul-christmas, pull requests merged in 2021-12, with the labels that each got.

#6 keep everything contained in the webpage
  index.html
  song_embed.js
Labels: enhancement, javascript

#24 End song, when the song user has chosen has ended.
  index.html
  index.js
Labels: enhancement, javascript

#25 move all lyrics to JS
  lyrics/alliwantforchristmas/index.html
  lyrics/alliwantforchristmas/index.js
  lyrics/babyitscoldoutside/index.html
  lyrics/babyitscoldoutside/index.js
  lyrics/christmassong/index.html
  lyrics/christmassong/index.js
  lyrics/lastchristmas/index.html
  lyrics/lastchristmas/index.js
  lyrics/littlesaintnick/index.html
  lyrics/littlesaintnick/index.js
  lyrics/wonderfultimeoftheyear/index.html
  lyrics/wonderfultimeoftheyear/index.js
  styles.css
Labels: enhancement, javascript, html

#42 fix #41
  _redirects
Labels: documentation

#50 Fixes#49
  README.md
  _redirects
Labels: documentation

#53 Fix#52
  otherprojects/index.html
  otherprojects/main.css
Labels: bug

#56 fix #55
  README.md
Labels: bug, documentation

#57 attempt to fix #54
  otherprojects/main.css
Labels: css

#48 Fixes issue #13 - updated styles.css
  index.js
  styles.css
Labels: javascript, css

#65 Fixes#51
  README.md
Labels: documentation, enhancement
