Repository KendallDoesCoding/mogul-christmas, pull requests merged in 2022-08, with the labels that each got.

#300 Fix the issue 103
  lyrics/alliwantforchristmas/index.js
  lyrics/alliwantforchristmas/lyrics.txt
  lyrics/babyitscoldoutside/index.js
  lyrics/christmassong/index.js
  lyrics/lastchristmas/index.js
  lyrics/littlesaintnick/index.js
  lyrics/lyrics.js
  lyrics/wonderfultimeoftheyear/index.js
Labels: size/M

#304 Converted .png to .jpg and updated HTML fixes#302
  images/photo-gallery-imgs/1.jpg
  images/photo-gallery-imgs/1.png
  images/photo-gallery-imgs/1.webp
  images/photo-gallery-imgs/2.jpg
  images/photo-gallery-imgs/2.png
  images/photo-gallery-imgs/2.webp
  images/photo-gallery-imgs/3.jpg
  images/photo-gallery-imgs/3.png
  images/photo-gallery-imgs/4.jpg
  images/photo-gallery-imgs/4.png
  images/photo-gallery-imgs/4.webp
  images/photo-gallery-imgs/7.jpg
  images/photo-gallery-imgs/7.png
  images/photo-gallery-imgs/8.jpg
  images/photo-gallery-imgs/8.png
  photo-gallery/index.html
Labels: size/S

#313 formatted readme file, added screenshots, contribution guideline
  README.md
  images/screenshots/ludwig-socials.jpg
  images/screenshots/mogul-christmas-1.jpg
  images/screenshots/mogul-christmas-dark-mode.jpg
  images/screenshots/photo-gallery.jpg
  images/screenshots/song-recommendations.jpg
  images/screenshots/video-with-lyrics.jpg
Labels: size/L

#315 redesigned the Rate Music page
  rating/index.html
  rating/index.js
  rating/photo1.jpeg
  rating/pink-wavy.jpg
  rating/styles.css
  rating/test.js
Labels: size/L
