Repository KendallDoesCoding/mogul-christmas, pull requests merged in 2022-01, with the labels that each got.

#88 Moved the lyrics to the lyrics.js file
  index.html
  lyrics/alliwantforchristmas/index.html
  lyrics/alliwantforchristmas/index.js
  lyrics/babyitscoldoutside/index.html
  lyrics/babyitscoldoutside/index.js
  lyrics/christmassong/index.html
  lyrics/christmassong/index.js
  lyrics/lastchristmas/index.html
  lyrics/lastchristmas/index.js
  lyrics/littlesaintnick/index.html
  lyrics/littlesaintnick/index.js
  lyrics/lyrics.js
  lyrics/wonderfultimeoftheyear/index.html
  lyrics/wonderfultimeoftheyear/index.js
Labels: javascript, in-progress

#101 Button to download a txt file of lyrics in all the songs in the lyrics directory, add missing lyrics
  lyrics/alliwantforchristmas/index.html
  lyrics/alliwantforchristmas/lyrics.txt
  lyrics/babyitscoldoutside/index.html
  lyrics/babyitscoldoutside/lyrics.txt
  lyrics/christmassong/index.html
  lyrics/christmassong/lyrics.txt
  lyrics/lastchristmas/index.html
  lyrics/lastchristmas/lyrics.txt
  lyrics/littlesaintnick/index.html
  lyrics/littlesaintnick/lyrics.txt
  lyrics/lyrics.js
  lyrics/wonderfultimeoftheyear/index.html
  lyrics/wonderfultimeoftheyear/lyrics.txt
  styles.css
Labels: enhancement, working-on

#109 Add releases in README.md
  README.md
  _redirects
Labels: documentation

#110 Adjust colors
  styles.css
Labels: css

#115 add > after </embed
  index.html
Labels: bug

#116 Remove extra code
  index.html
Labels: testings

#83 Make website more responsive, remove Christmas trees from lyrics.
  index.js
  lyrics/index.html
  styles.css
Labels: bug, enhancement, css, working-on

#120 Ludwig Socials page, linked via a button on main page, format all css, capitalize all color codes
  index.html
  ludsocials/index.html
  ludsocials/podcasts/apple-brands.svg
  ludsocials/podcasts/images/theyard.jfif
  ludsocials/podcasts/index.html
  ludsocials/podcasts/spotify-brands.svg
  ludsocials/podcasts/styles.css
  otherprojects/main.css
  styles.css
Labels: enhancement

#124 Format HTML, remove extra lines
  index.html
  ludsocials/index.html
  ludsocials/podcasts/index.html
  lyrics/alliwantforchristmas/index.html
  lyrics/babyitscoldoutside/index.html
  lyrics/christmassong/index.html
  lyrics/index.html
  lyrics/lastchristmas/index.html
  lyrics/littlesaintnick/index.html
  lyrics/wonderfultimeoftheyear/index.html
  otherprojects/index.html
Labels: html

#133 Move darkmode to Javascript instead of the script tag in HTML
  ludsocials/darkmode.js
  ludsocials/index.html
  lyrics/darkmode.js
  lyrics/index.html
Labels: enhancement

#136 Disable text-selection on site
  styles.css
Labels: enhancement

#140 Make socials button a little darker orange.
  styles.css
Labels: css

#141 Make js file name in scripts lowercase.
  index.html
  scripts/christmasday.js
Labels: enhancement, javascript, feedback, html

#148 fix #147
  otherprojects/main.css
Labels: enhancement

#149 Format, JS, HTML, CSS code
  index.js
  ludsocials/index.html
  lyrics/index.html
  lyrics/lyrics.js
  otherprojects/main.css
  scripts/christmasday.js
Labels: javascript, html, css

#156 End embed from playing song after song is over in the lyrics directory, don't start the next song.
  lyrics/alliwantforchristmas/index.html
  lyrics/babyitscoldoutside/index.html
  lyrics/christmassong/index.html
  lyrics/lastchristmas/index.html
  lyrics/littlesaintnick/index.html
  lyrics/wonderfultimeoftheyear/index.html
Labels: enhancement

#150 Add cover image on the button of "Christmas Album by Ludwig"
  images/cover.jpg
  index.html
Labels: enhancement

#162 Add cover image on the button of "Christmas Album by Ludwig"
  images/cover.jpg
  index.html
Labels: enhancement

#158 update lyrics color
  styles.css
Labels: feedback, working-on

#171 update lyrics color
  styles.css
Labels: enhancement, feedback

#180 Enhance branch code fix #177
  styles.css
  you-may-like/index.html
Labels: testings

#145 Call the christmas tree images in a separate element instead of in the body
  index.html
  lyrics/alliwantforchristmas/index.html
  lyrics/babyitscoldoutside/index.html
  lyrics/christmassong/index.html
  lyrics/index.html
  lyrics/lastchristmas/index.html
  lyrics/littlesaintnick/index.html
  lyrics/wonderfultimeoftheyear/index.html
  styles.css
Labels: enhancement
