Repository KendallDoesCoding/mogul-christmas, pull requests merged in 2022-10, with the labels that each got.

#334 block user from selecting text on rating page
  rating/styles.css
Labels: size/XS

#335 Background Update for Rating Song
  rating/landscape.jpg
  rating/photo1.jpeg
  rating/portrait.jpg
  rating/styles.css
Labels: size/S

#336 Added Navbar to the Website.
  index.html
  index.js
  styles.css
Labels: size/XL

#339 added darkmode persistance; improved code quality
  index.js
Labels: size/M
