Repository KendallDoesCoding/mogul-christmas, pull requests merged in 2022-03, with the labels that each got.

#240 Add work done by by contributors in the project under their name in Credits directory.
  credits/index.html
  credits/styles.css
Labels: enhancement, html, css

#245 Rate song button
  index.html
  lyrics/alliwantforchristmas/index.html
  lyrics/babyitscoldoutside/index.html
  lyrics/christmassong/index.html
  lyrics/lastchristmas/index.html
  lyrics/littlesaintnick/index.html
  lyrics/wonderfultimeoftheyear/index.html
  rating/index.html
  rating/styles.css
  styles.css
Labels: enhancement

#246 docs: added PR template
  .github/pull_request_template.md
Labels: documentation, enhancement

#248 Add Christmas Background image
  images/dark-bg.png
  images/light-bg.png
  index.html
  lyrics/alliwantforchristmas/index.html
  lyrics/babyitscoldoutside/index.html
  lyrics/christmassong/index.html
  lyrics/index.html
  lyrics/lastchristmas/index.html
  lyrics/littlesaintnick/index.html
  lyrics/wonderfultimeoftheyear/index.html
  styles.css
  you-may-like/index.html
Labels: enhancement

#253 Add info via image form in readme
  README.md
Labels: documentation, enhancement, image
