Repository KendallDoesCoding/mogul-christmas, pull requests merged in 2022-09, with the labels that each got.

#318 png to jpg Gh-action image converter
  .github/workflows/imagesConverter.yml
Labels: size/S

#320 Fixed Links in song suggestion pagination
  you-may-like/index.js
Labels: size/L

#327 Stop music feature
  index.html
  index.js
  styles.css
Labels: size/M

#328 Fixed grammatical error and added photo to photo gallery.
  README.md
  images/photo-gallery-imgs/10.jpg
  index.html
  photo-gallery/index.html
  styles.css
Labels: size/S

#332 Loop feature (addressing issue #187)
  index.html
  index.js
  styles.css
Labels: size/L
