Repository KendallDoesCoding/mogul-christmas, pull requests merged in 2023-04, with the labels that each got.

#364 wrote comments for some of HTML & JS codes
  credits/index.html
  credits/styles.css
  index.js
  ludsocials/index.html
  ludsocials/podcasts/index.html
  lyrics/alliwantforchristmas/index.js
  lyrics/babyitscoldoutside/index.js
  lyrics/christmassong/index.html
  lyrics/christmassong/index.js
  lyrics/darkmode.js
  lyrics/index.html
  lyrics/lastchristmas/index.html
  news-articles/index.html
  scripts/christmasday.js
  scripts/otherProjects.js
  you-may-like/darkmode.js
  you-may-like/index.html
  you-may-like/index.js
Labels: size/L

#368 Added Dropdown option , FIXES #367
  credits/index.html
  credits/styles.css
Labels: size/L

#372 added comments to files from rating
  credits/styles.css
  rating/index.html
  rating/styles.css
  you-may-like/index.html
  you-may-like/song-suggestion/index.html
  you-may-like/styles.css
Labels: size/S

#377 Fix Navigation Bar
  index.html
  index.js
  styles.css
Labels: size/M

#378 Fix Navbar Add Return buttons
  credits/index.html
  credits/styles.css
  index.html
  styles.css
Labels: size/S

#382 modified style of suggestion page
  you-may-like/song-suggestion/index.html
  you-may-like/song-suggestion/styles.css
Labels: size/M

#384 Modified report-song-page
  you-may-like/report-song/index.html
  you-may-like/report-song/styles.css
Labels: size/M

#387 Changed color of days until Christmas for darkmode
  styles.css
Labels: size/XS

#390 changed ssh to SSH and Cli to CLI in README.md
  README.md
Labels: size/XS
